name: rv-dev
channels:
  - pytorch
  - conda-forge
  - defaults
  # - fastai
dependencies:
  - python=3.9
  - numpy
  - pillow
  - torch
  - torchvision
  - tensorboard
  - albumentations
  - cython
  - pycocotools
  - psutil
  - triangle
  - opencv-python
  - opencv-python-headless
  - matplotlib
  - tqdm
  - click
  - pydantic
  - typing_extensions
  - everett
  - six
  - pygeos
  - shapely
  - geopandas
  - pyproj
  - rasterio
  - imageio
  - pystac
  - scikit-learn
  - scipy
  - pip:
      - -e . # install git checkout of current directory in editable mode

  
