name: rv-dev
channels:
  - pytorch
  - conda-forge
  - defaults
  # - fastai
dependencies:
  - albumentations
  - click
  - cython
  - everett
  - geopandas
  - imageio
  - matplotlib
  - numpy
  - opencv-python
  - opencv-python-headless
  - pillow
  - psutil
  - pycocotools
  - pydantic
  - pygeos
  - pyproj
  - pystac
  - python=3.9
  - rasterio
  - scikit-learn
  - scipy
  - shapely
  - six
  - tensorboard
  - torch
  - torchvision
  - tqdm
  - triangle
  - typing_extensions
  - pip:
      - -e . # install git checkout of current directory in editable mode
# From the requirements-dev.txt
  - codecov
  - coverage
  - flake8
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - moto
  - seaborn
  - sphinx-autobuild
  - unify
  - yapf

  
