name: rv-dev
channels:
  # - fastchan
  - conda-forge
  - pytorch
  - nvidia
  - defaults
  # - fastai
dependencies:
  - albumentations
  - click
  - configobj # required for everett[ini]
  - cython
  - everett
  - gdal=3.5.2
  - geopandas
  - imageio
  - matplotlib
  - numpy=1.23
  # - opencv=4.6.0
  # - opencv-python
  # - opencv-python-headless
  - pillow
  - pip
  - psutil
  - pycocotools
  - pydantic
  - pygeos
  - pyproj
  - pystac
  - python=3.9
  - rasterio
  - scikit-learn
  - scipy
  - shapely
  - six
  - tensorboard
  # - torch
  - pytorch
  - pytorch-cuda=11.6
  - torchvision
  - tqdm
  - triangle
  - typing_extensions
  - pip:
      # Order taken from https://docs.rastervision.io/en/latest/release.html
      - -e ./rastervision_pipeline
      - -e ./rastervision_aws_s3
      - -e ./rastervision_aws_batch
      - -e ./rastervision_core
      - -e ./rastervision_pytorch_learner
      - -e ./rastervision_pytorch_backend
      - -e ./rastervision_gdal_vsi
      - -e . # install git checkout of current directory in editable mode
# From the requirements-dev.txt
  - codecov
  - coverage
  - flake8
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - moto
  - seaborn
  - sphinx-autobuild
  - unify
  - yapf

  
