name: rv-dev
channels:
  # - fastchan
  - conda-forge
  - pytorch
  - nvidia
  - defaults
  # - fastai
dependencies:
  - albumentations
  - boto3
  - click
  - configobj # required for everett[ini]
  - cython
  - everett
  - gdal=3.5.2
  - geopandas
  - imageio
  - matplotlib
  - numpy=1.23
  # - opencv=4.6.0
  # - opencv-python
  # - opencv-python-headless
  - pillow
  - pip
  - psutil
  - pycocotools
  - pydantic
  - pygeos
  - pyproj
  - pystac
  - python=3.9
  - rasterio
  - scikit-learn
  - scipy
  - shapely
  - six
  - tensorboard
  # - torch
  - pytorch
  - pytorch-cuda=11.6
  - torchvision
  - tqdm
  - triangle
  - typing_extensions
# From the requirements-dev.txt
  - codecov
  - coverage
  - flake8
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  # - moto # Do not install! Will break jupyter due to req: sonschema ~=3.2
  - seaborn
  - sphinx-autobuild
  - unify
  - yapf
# owns
  - spyder
  - spyder-kernels
  # - pip:
  #     # Order taken from https://docs.rastervision.io/en/latest/release.html
  #     - "--no-deps -e ./rastervision_pipeline"
  #     - "--no-deps -e ./rastervision_aws_s3"
  #     - "--no-deps -e ./rastervision_aws_batch"
  #     - "--no-deps -e ./rastervision_core"
  #     - "--no-deps -e ./rastervision_pytorch_learner"
  #     - "--no-deps -e ./rastervision_pytorch_backend"
  #     - "--no-deps -e ./rastervision_gdal_vsi"
  #     - "--no-deps -e ."  # install git checkout of current directory in editable mode

  
